services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      - mediastack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=${SERVER_URL} # autodiscovery
    volumes:
      - ${BASE_DIR}/config/jellyfin:/config
      - ${TV_DIR}:/data/tvshows
      - ${MOVIE_DIR}:/data/movies
    ports:
      - 8096:8096
      # - 8920:8920 # optional for https webUI, need to set up own ceritificate
      - 7359:7359/udp # autodiscovery
      - 1900:1900/udp # autodiscovery
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    networks:
      - mediastack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_URL=http://jellyfin:8096
    volumes:
      - ${BASE_DIR}/config/jellyseerr:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - mediastack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - RADARR__AUTHENTICATION_METHOD=External
      - RADARR__AUTHENTICATION_REQUIRED=Disabled
    volumes:
      - ${BASE_DIR}/config/radarr:/config
      - ${BASE_DIR}/media:/media
      - ${BASE_DIR}/downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - mediastack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SONARR__AUTHENTICATION_METHOD=External
      - SONARR__AUTHENTICATION_REQUIRED=Disabled
    volumes:
      - ${BASE_DIR}/config/sonarr:/config
      - ${BASE_DIR}/media:/media
      - ${BASE_DIR}/downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - mediastack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}/config/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - mediastack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${BASE_DIR}/config/qbittorrent:/config
      - ${BASE_DIR}/downloads:/downloads
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - mediastack
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}/config/bazarr:/config
      - ${BASE_DIR}/media:/media
    ports:
      - "6767:6767"
    restart: unless-stopped

  # Optional, to be able to use certain indexers in Prowlarr
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - mediastack
    environment:
      - LOG_LEVEL=info
    volumes:
      - ${BASE_DIR}/config/flaresolverr:/config
    ports:
      - "8091:8091"
    restart: unless-stopped

networks:
  mediastack:
    driver: bridge
    name: mediastack
